portplan.pdf: portplan.tex
	pdflatex portplan
	pdflatex portplan
	pdflatex portplan
             
clean:     
	rm -fr auto
	rm -f portplan.aux portplan.bbl portplan.blg portplan.log portplan.pdf portplan.out
